graph TD
    Beverages["Beverages"]
    1_Low_Fat_Milk_Jug["1% Low Fat Milk Jug"]
    Beverages --> 1_Low_Fat_Milk_Jug
    Coca_Cola_Classic_Child["Coca-Cola Classic (Child)"]
    Beverages --> Coca_Cola_Classic_Child
    Coca_Cola_Classic_Large["Coca-Cola Classic (Large)"]
    Beverages --> Coca_Cola_Classic_Large
    Coca_Cola_Classic_Medium["Coca-Cola Classic (Medium)"]
    Beverages --> Coca_Cola_Classic_Medium
    Coca_Cola_Classic_Small["Coca-Cola Classic (Small)"]
    Beverages --> Coca_Cola_Classic_Small
    Dasani_Water_Bottle["Dasani Water Bottle"]
    Beverages --> Dasani_Water_Bottle
    Diet_Coke_Child["Diet Coke (Child)"]
    Beverages --> Diet_Coke_Child
    Diet_Coke_Large["Diet Coke (Large)"]
    Beverages --> Diet_Coke_Large
    Diet_Coke_Medium["Diet Coke (Medium)"]
    Beverages --> Diet_Coke_Medium
    Diet_Coke_Small["Diet Coke (Small)"]
    Beverages --> Diet_Coke_Small
    Diet_Dr_Pepper_Child["Diet Dr Pepper (Child)"]
    Beverages --> Diet_Dr_Pepper_Child
    Diet_Dr_Pepper_Large["Diet Dr Pepper (Large)"]
    Beverages --> Diet_Dr_Pepper_Large
    Diet_Dr_Pepper_Medium["Diet Dr Pepper (Medium)"]
    Beverages --> Diet_Dr_Pepper_Medium
    Diet_Dr_Pepper_Small["Diet Dr Pepper (Small)"]
    Beverages --> Diet_Dr_Pepper_Small
    Dr_Pepper_Child["Dr Pepper (Child)"]
    Beverages --> Dr_Pepper_Child
    Dr_Pepper_Large["Dr Pepper (Large)"]
    Beverages --> Dr_Pepper_Large
    Dr_Pepper_Medium["Dr Pepper (Medium)"]
    Beverages --> Dr_Pepper_Medium
    Dr_Pepper_Small["Dr Pepper (Small)"]
    Beverages --> Dr_Pepper_Small
    Fat_Free_Chocolate_Milk_Jug["Fat Free Chocolate Milk Jug"]
    Beverages --> Fat_Free_Chocolate_Milk_Jug
    Minute_Maid_100_Apple_Juice_Box["Minute Maid 100% Apple Juice Box"]
    Beverages --> Minute_Maid_100_Apple_Juice_Box
    Minute_Maid_Orange_Juice_Large["Minute Maid Orange Juice (Large)"]
    Beverages --> Minute_Maid_Orange_Juice_Large
    Minute_Maid_Orange_Juice_Medium["Minute Maid Orange Juice (Medium)"]
    Beverages --> Minute_Maid_Orange_Juice_Medium
    Minute_Maid_Orange_Juice_Small["Minute Maid Orange Juice (Small)"]
    Beverages --> Minute_Maid_Orange_Juice_Small
    Sprite_Child["Sprite (Child)"]
    Beverages --> Sprite_Child
    Sprite_Large["Sprite (Large)"]
    Beverages --> Sprite_Large
    Sprite_Medium["Sprite (Medium)"]
    Beverages --> Sprite_Medium
    Sprite_Small["Sprite (Small)"]
    Beverages --> Sprite_Small