graph TD
    Breakfast["Breakfast"]
    Bacon["Bacon"]
    Breakfast --> Bacon
    Big_Breakfast_Large_Biscuit["Big Breakfast (Large Biscuit)"]
    Breakfast --> Big_Breakfast_Large_Biscuit
    Big_Breakfast_Large_Biscuit_Egg_Whites["add Egg Whites"]
    Big_Breakfast_Large_Biscuit --> Big_Breakfast_Large_Biscuit_Egg_Whites
    Big_Breakfast_Large_Biscuit_Hotcakes["add Hotcakes"]
    Big_Breakfast_Large_Biscuit --> Big_Breakfast_Large_Biscuit_Hotcakes
    Big_Breakfast_Large_Biscuit_Hotcakes_and_Egg_Whites["add Hotcakes and Egg Whites"]
    Big_Breakfast_Large_Biscuit --> Big_Breakfast_Large_Biscuit_Hotcakes_and_Egg_Whites
    Big_Breakfast_Regular_Biscuit["Big Breakfast (Regular Biscuit)"]
    Breakfast --> Big_Breakfast_Regular_Biscuit
    Big_Breakfast_Regular_Biscuit_Egg_Whites["add Egg Whites"]
    Big_Breakfast_Regular_Biscuit --> Big_Breakfast_Regular_Biscuit_Egg_Whites
    Big_Breakfast_Regular_Biscuit_Hotcakes["add Hotcakes"]
    Big_Breakfast_Regular_Biscuit --> Big_Breakfast_Regular_Biscuit_Hotcakes
    Big_Breakfast_Regular_Biscuit_Hotcakes_and_Egg_Whites["add Hotcakes and Egg Whites"]
    Big_Breakfast_Regular_Biscuit --> Big_Breakfast_Regular_Biscuit_Hotcakes_and_Egg_Whites
    Cinnamon_Melts["Cinnamon Melts"]
    Breakfast --> Cinnamon_Melts
    Egg_McMuffin["Egg McMuffin"]
    Breakfast --> Egg_McMuffin
    Egg_White_Delight["Egg White Delight"]
    Breakfast --> Egg_White_Delight
    Fruit_Maple_Oatmeal["Fruit & Maple Oatmeal"]
    Breakfast --> Fruit_Maple_Oatmeal
    Fruit_Maple_Oatmeal_without_Brown_Sugar["without Brown Sugar"]
    Fruit_Maple_Oatmeal --> Fruit_Maple_Oatmeal_without_Brown_Sugar
    Fruit_Maple_Oatmeal_without_Brown_Sugar["Fruit & Maple Oatmeal without Brown Sugar"]
    Breakfast --> Fruit_Maple_Oatmeal_without_Brown_Sugar
    Hash_Brown["Hash Brown"]
    Breakfast --> Hash_Brown
    Hotcakes["Hotcakes"]
    Breakfast --> Hotcakes
    Hotcakes_and_Sausage["Hotcakes and Sausage"]
    Breakfast --> Hotcakes_and_Sausage
    Sausage["Sausage"]
    Breakfast --> Sausage
    Sausage_Biscuit_Large_Biscuit["Sausage Biscuit (Large Biscuit)"]
    Breakfast --> Sausage_Biscuit_Large_Biscuit
    Sausage_Biscuit_Large_Biscuit_Egg["add Egg"]
    Sausage_Biscuit_Large_Biscuit --> Sausage_Biscuit_Large_Biscuit_Egg
    Sausage_Biscuit_Large_Biscuit_Egg_Whites["add Egg Whites"]
    Sausage_Biscuit_Large_Biscuit --> Sausage_Biscuit_Large_Biscuit_Egg_Whites
    Sausage_Biscuit_Regular_Biscuit["Sausage Biscuit (Regular Biscuit)"]
    Breakfast --> Sausage_Biscuit_Regular_Biscuit
    Sausage_Biscuit_Regular_Biscuit_Egg["add Egg"]
    Sausage_Biscuit_Regular_Biscuit --> Sausage_Biscuit_Regular_Biscuit_Egg
    Sausage_Biscuit_Regular_Biscuit_Egg_Whites["add Egg Whites"]
    Sausage_Biscuit_Regular_Biscuit --> Sausage_Biscuit_Regular_Biscuit_Egg_Whites
    Sausage_Burrito["Sausage Burrito"]
    Breakfast --> Sausage_Burrito
    Sausage_McGriddles["Sausage McGriddles"]
    Breakfast --> Sausage_McGriddles
    Sausage_McMuffin["Sausage McMuffin"]
    Breakfast --> Sausage_McMuffin
    Sausage_McMuffin_Egg["add Egg"]
    Sausage_McMuffin --> Sausage_McMuffin_Egg
    Sausage_McMuffin_Egg_Whites["add Egg Whites"]
    Sausage_McMuffin --> Sausage_McMuffin_Egg_Whites
    Southern_Style_Chicken_Biscuit_Large_Biscuit["Southern Style Chicken Biscuit (Large Biscuit)"]
    Breakfast --> Southern_Style_Chicken_Biscuit_Large_Biscuit
    Southern_Style_Chicken_Biscuit_Regular_Biscuit["Southern Style Chicken Biscuit (Regular Biscuit)"]
    Breakfast --> Southern_Style_Chicken_Biscuit_Regular_Biscuit
    Steak["Steak"]
    Breakfast --> Steak
    Steak_Egg_Biscuit_Regular_Biscuit["Steak & Egg Biscuit (Regular Biscuit)"]
    Breakfast --> Steak_Egg_Biscuit_Regular_Biscuit
    Steak_Egg_McMuffin["Steak & Egg McMuffin"]
    Breakfast --> Steak_Egg_McMuffin