graph TD
    Chicken_Fish["Chicken & Fish"]
    Bacon_Buffalo_Ranch_McChicken["Bacon Buffalo Ranch McChicken"]
    Chicken_Fish --> Bacon_Buffalo_Ranch_McChicken
    Bacon_Cheddar_McChicken["Bacon Cheddar McChicken"]
    Chicken_Fish --> Bacon_Cheddar_McChicken
    Bacon_Clubhouse_Crispy_Chicken_Sandwich["Bacon Clubhouse Crispy Chicken Sandwich"]
    Chicken_Fish --> Bacon_Clubhouse_Crispy_Chicken_Sandwich
    Bacon_Clubhouse_Grilled_Chicken_Sandwich["Bacon Clubhouse Grilled Chicken Sandwich"]
    Chicken_Fish --> Bacon_Clubhouse_Grilled_Chicken_Sandwich
    Buffalo_Ranch_McChicken["Buffalo Ranch McChicken"]
    Chicken_Fish --> Buffalo_Ranch_McChicken
    Chicken_McNuggets_10_piece["Chicken McNuggets (10 piece)"]
    Chicken_Fish --> Chicken_McNuggets_10_piece
    Chicken_McNuggets_20_piece["Chicken McNuggets (20 piece)"]
    Chicken_Fish --> Chicken_McNuggets_20_piece
    Chicken_McNuggets_4_piece["Chicken McNuggets (4 piece)"]
    Chicken_Fish --> Chicken_McNuggets_4_piece
    Chicken_McNuggets_40_piece["Chicken McNuggets (40 piece)"]
    Chicken_Fish --> Chicken_McNuggets_40_piece
    Chicken_McNuggets_6_piece["Chicken McNuggets (6 piece)"]
    Chicken_Fish --> Chicken_McNuggets_6_piece
    Filet_O_Fish["Filet-O-Fish"]
    Chicken_Fish --> Filet_O_Fish
    McChicken["McChicken"]
    Chicken_Fish --> McChicken
    Premium_Crispy_Chicken_Classic_Sandwich["Premium Crispy Chicken Classic Sandwich"]
    Chicken_Fish --> Premium_Crispy_Chicken_Classic_Sandwich
    Premium_Crispy_Chicken_Club_Sandwich["Premium Crispy Chicken Club Sandwich"]
    Chicken_Fish --> Premium_Crispy_Chicken_Club_Sandwich
    Premium_Crispy_Chicken_Ranch_BLT_Sandwich["Premium Crispy Chicken Ranch BLT Sandwich"]
    Chicken_Fish --> Premium_Crispy_Chicken_Ranch_BLT_Sandwich
    Premium_Grilled_Chicken_Classic_Sandwich["Premium Grilled Chicken Classic Sandwich"]
    Chicken_Fish --> Premium_Grilled_Chicken_Classic_Sandwich
    Premium_Grilled_Chicken_Club_Sandwich["Premium Grilled Chicken Club Sandwich"]
    Chicken_Fish --> Premium_Grilled_Chicken_Club_Sandwich
    Premium_Grilled_Chicken_Ranch_BLT_Sandwich["Premium Grilled Chicken Ranch BLT Sandwich"]
    Chicken_Fish --> Premium_Grilled_Chicken_Ranch_BLT_Sandwich
    Premium_McWrap_Chicken_Bacon_Crispy_Chicken["Premium McWrap Chicken & Bacon (Crispy Chicken)"]
    Chicken_Fish --> Premium_McWrap_Chicken_Bacon_Crispy_Chicken
    Premium_McWrap_Chicken_Bacon_Grilled_Chicken["Premium McWrap Chicken & Bacon (Grilled Chicken)"]
    Chicken_Fish --> Premium_McWrap_Chicken_Bacon_Grilled_Chicken
    Premium_McWrap_Chicken_Ranch_Crispy_Chicken["Premium McWrap Chicken & Ranch (Crispy Chicken)"]
    Chicken_Fish --> Premium_McWrap_Chicken_Ranch_Crispy_Chicken
    Premium_McWrap_Chicken_Ranch_Grilled_Chicken["Premium McWrap Chicken & Ranch (Grilled Chicken)"]
    Chicken_Fish --> Premium_McWrap_Chicken_Ranch_Grilled_Chicken
    Premium_McWrap_Chicken_Sweet_Chili_Crispy_Chicken["Premium McWrap Chicken Sweet Chili (Crispy Chicken)"]
    Chicken_Fish --> Premium_McWrap_Chicken_Sweet_Chili_Crispy_Chicken
    Premium_McWrap_Chicken_Sweet_Chili_Grilled_Chicken["Premium McWrap Chicken Sweet Chili (Grilled Chicken)"]
    Chicken_Fish --> Premium_McWrap_Chicken_Sweet_Chili_Grilled_Chicken
    Premium_McWrap_Southwest_Chicken_Crispy_Chicken["Premium McWrap Southwest Chicken (Crispy Chicken)"]
    Chicken_Fish --> Premium_McWrap_Southwest_Chicken_Crispy_Chicken
    Premium_McWrap_Southwest_Chicken_Grilled_Chicken["Premium McWrap Southwest Chicken (Grilled Chicken)"]
    Chicken_Fish --> Premium_McWrap_Southwest_Chicken_Grilled_Chicken
    Southern_Style_Crispy_Chicken_Sandwich["Southern Style Crispy Chicken Sandwich"]
    Chicken_Fish --> Southern_Style_Crispy_Chicken_Sandwich