graph TD
    Coffee_Tea["Coffee & Tea"]
    Caramel_Iced_Coffee_Large["Caramel Iced Coffee (Large)"]
    Coffee_Tea --> Caramel_Iced_Coffee_Large
    Caramel_Iced_Coffee_Medium["Caramel Iced Coffee (Medium)"]
    Coffee_Tea --> Caramel_Iced_Coffee_Medium
    Caramel_Iced_Coffee_Small["Caramel Iced Coffee (Small)"]
    Coffee_Tea --> Caramel_Iced_Coffee_Small
    Caramel_Latte_Large["Caramel Latte (Large)"]
    Coffee_Tea --> Caramel_Latte_Large
    Caramel_Latte_Medium["Caramel Latte (Medium)"]
    Coffee_Tea --> Caramel_Latte_Medium
    Caramel_Latte_Small["Caramel Latte (Small)"]
    Coffee_Tea --> Caramel_Latte_Small
    Caramel_Mocha_Large["Caramel Mocha (Large)"]
    Coffee_Tea --> Caramel_Mocha_Large
    Caramel_Mocha_Medium["Caramel Mocha (Medium)"]
    Coffee_Tea --> Caramel_Mocha_Medium
    Caramel_Mocha_Small["Caramel Mocha (Small)"]
    Coffee_Tea --> Caramel_Mocha_Small
    Coffee_Large["Coffee (Large)"]
    Coffee_Tea --> Coffee_Large
    Coffee_Medium["Coffee (Medium)"]
    Coffee_Tea --> Coffee_Medium
    Coffee_Small["Coffee (Small)"]
    Coffee_Tea --> Coffee_Small
    Frapp_Caramel_Large["Frappé Caramel (Large)"]
    Coffee_Tea --> Frapp_Caramel_Large
    Frapp_Caramel_Medium["Frappé Caramel (Medium)"]
    Coffee_Tea --> Frapp_Caramel_Medium
    Frapp_Caramel_Small["Frappé Caramel (Small)"]
    Coffee_Tea --> Frapp_Caramel_Small
    Frapp_Chocolate_Chip_Large["Frappé Chocolate Chip (Large)"]
    Coffee_Tea --> Frapp_Chocolate_Chip_Large
    Frapp_Chocolate_Chip_Medium["Frappé Chocolate Chip (Medium)"]
    Coffee_Tea --> Frapp_Chocolate_Chip_Medium
    Frapp_Chocolate_Chip_Small["Frappé Chocolate Chip (Small)"]
    Coffee_Tea --> Frapp_Chocolate_Chip_Small
    Frapp_Mocha_Large["Frappé Mocha (Large)"]
    Coffee_Tea --> Frapp_Mocha_Large
    Frapp_Mocha_Medium["Frappé Mocha (Medium)"]
    Coffee_Tea --> Frapp_Mocha_Medium
    Frapp_Mocha_Small["Frappé Mocha (Small)"]
    Coffee_Tea --> Frapp_Mocha_Small
    French_Vanilla_Iced_Coffee_Large["French Vanilla Iced Coffee (Large)"]
    Coffee_Tea --> French_Vanilla_Iced_Coffee_Large
    French_Vanilla_Iced_Coffee_Medium["French Vanilla Iced Coffee (Medium)"]
    Coffee_Tea --> French_Vanilla_Iced_Coffee_Medium
    French_Vanilla_Iced_Coffee_Small["French Vanilla Iced Coffee (Small)"]
    Coffee_Tea --> French_Vanilla_Iced_Coffee_Small
    French_Vanilla_Latte_Large["French Vanilla Latte (Large)"]
    Coffee_Tea --> French_Vanilla_Latte_Large
    French_Vanilla_Latte_Medium["French Vanilla Latte (Medium)"]
    Coffee_Tea --> French_Vanilla_Latte_Medium
    French_Vanilla_Latte_Small["French Vanilla Latte (Small)"]
    Coffee_Tea --> French_Vanilla_Latte_Small
    Hazelnut_Iced_Coffee_Large["Hazelnut Iced Coffee (Large)"]
    Coffee_Tea --> Hazelnut_Iced_Coffee_Large
    Hazelnut_Iced_Coffee_Medium["Hazelnut Iced Coffee (Medium)"]
    Coffee_Tea --> Hazelnut_Iced_Coffee_Medium
    Hazelnut_Iced_Coffee_Small["Hazelnut Iced Coffee (Small)"]
    Coffee_Tea --> Hazelnut_Iced_Coffee_Small
    Hazelnut_Latte_Large["Hazelnut Latte (Large)"]
    Coffee_Tea --> Hazelnut_Latte_Large
    Hazelnut_Latte_Medium["Hazelnut Latte (Medium)"]
    Coffee_Tea --> Hazelnut_Latte_Medium
    Hazelnut_Latte_Small["Hazelnut Latte (Small)"]
    Coffee_Tea --> Hazelnut_Latte_Small
    Hot_Chocolate_Large["Hot Chocolate (Large)"]
    Coffee_Tea --> Hot_Chocolate_Large
    Hot_Chocolate_Large_Nonfat_Milk["add Nonfat Milk"]
    Hot_Chocolate_Large --> Hot_Chocolate_Large_Nonfat_Milk
    Hot_Chocolate_Medium["Hot Chocolate (Medium)"]
    Coffee_Tea --> Hot_Chocolate_Medium
    Hot_Chocolate_Medium_Nonfat_Milk["add Nonfat Milk"]
    Hot_Chocolate_Medium --> Hot_Chocolate_Medium_Nonfat_Milk
    Hot_Chocolate_Small["Hot Chocolate (Small)"]
    Coffee_Tea --> Hot_Chocolate_Small
    Hot_Chocolate_Small_Nonfat_Milk["add Nonfat Milk"]
    Hot_Chocolate_Small --> Hot_Chocolate_Small_Nonfat_Milk
    Iced_Caramel_Mocha_Large["Iced Caramel Mocha (Large)"]
    Coffee_Tea --> Iced_Caramel_Mocha_Large
    Iced_Caramel_Mocha_Medium["Iced Caramel Mocha (Medium)"]
    Coffee_Tea --> Iced_Caramel_Mocha_Medium
    Iced_Caramel_Mocha_Small["Iced Caramel Mocha (Small)"]
    Coffee_Tea --> Iced_Caramel_Mocha_Small
    Iced_Coffee_Large["Iced Coffee (Large)"]
    Coffee_Tea --> Iced_Coffee_Large
    Iced_Coffee_Large_Sugar_Free_French_Vanilla_Syrup["add Sugar Free French Vanilla Syrup"]
    Iced_Coffee_Large --> Iced_Coffee_Large_Sugar_Free_French_Vanilla_Syrup
    Iced_Coffee_Medium["Iced Coffee (Medium)"]
    Coffee_Tea --> Iced_Coffee_Medium
    Iced_Coffee_Medium_Sugar_Free_French_Vanilla_Syrup["add Sugar Free French Vanilla Syrup"]
    Iced_Coffee_Medium --> Iced_Coffee_Medium_Sugar_Free_French_Vanilla_Syrup
    Iced_Coffee_Small["Iced Coffee (Small)"]
    Coffee_Tea --> Iced_Coffee_Small
    Iced_Coffee_Small_Sugar_Free_French_Vanilla_Syrup["add Sugar Free French Vanilla Syrup"]
    Iced_Coffee_Small --> Iced_Coffee_Small_Sugar_Free_French_Vanilla_Syrup
    Iced_Mocha_Large["Iced Mocha (Large)"]
    Coffee_Tea --> Iced_Mocha_Large
    Iced_Mocha_Large_Nonfat_Milk["add Nonfat Milk"]
    Iced_Mocha_Large --> Iced_Mocha_Large_Nonfat_Milk
    Iced_Mocha_Medium["Iced Mocha (Medium)"]
    Coffee_Tea --> Iced_Mocha_Medium
    Iced_Mocha_Medium_Nonfat_Milk["add Nonfat Milk"]
    Iced_Mocha_Medium --> Iced_Mocha_Medium_Nonfat_Milk
    Iced_Mocha_Small["Iced Mocha (Small)"]
    Coffee_Tea --> Iced_Mocha_Small
    Iced_Mocha_Small_Nonfat_Milk["add Nonfat Milk"]
    Iced_Mocha_Small --> Iced_Mocha_Small_Nonfat_Milk
    Iced_Nonfat_Caramel_Mocha_Large["Iced Nonfat Caramel Mocha (Large)"]
    Coffee_Tea --> Iced_Nonfat_Caramel_Mocha_Large
    Iced_Nonfat_Caramel_Mocha_Medium["Iced Nonfat Caramel Mocha (Medium)"]
    Coffee_Tea --> Iced_Nonfat_Caramel_Mocha_Medium
    Iced_Nonfat_Caramel_Mocha_Small["Iced Nonfat Caramel Mocha (Small)"]
    Coffee_Tea --> Iced_Nonfat_Caramel_Mocha_Small
    Iced_Tea_Child["Iced Tea (Child)"]
    Coffee_Tea --> Iced_Tea_Child
    Iced_Tea_Large["Iced Tea (Large)"]
    Coffee_Tea --> Iced_Tea_Large
    Iced_Tea_Medium["Iced Tea (Medium)"]
    Coffee_Tea --> Iced_Tea_Medium
    Iced_Tea_Small["Iced Tea (Small)"]
    Coffee_Tea --> Iced_Tea_Small
    Latte_Large["Latte (Large)"]
    Coffee_Tea --> Latte_Large
    Latte_Large_Sugar_Free_French_Vanilla_Syrup["add Sugar Free French Vanilla Syrup"]
    Latte_Large --> Latte_Large_Sugar_Free_French_Vanilla_Syrup
    Latte_Medium["Latte (Medium)"]
    Coffee_Tea --> Latte_Medium
    Latte_Medium_Sugar_Free_French_Vanilla_Syrup["add Sugar Free French Vanilla Syrup"]
    Latte_Medium --> Latte_Medium_Sugar_Free_French_Vanilla_Syrup
    Latte_Small["Latte (Small)"]
    Coffee_Tea --> Latte_Small
    Latte_Small_Sugar_Free_French_Vanilla_Syrup["add Sugar Free French Vanilla Syrup"]
    Latte_Small --> Latte_Small_Sugar_Free_French_Vanilla_Syrup
    Mocha_Large["Mocha (Large)"]
    Coffee_Tea --> Mocha_Large
    Mocha_Large_Nonfat_Milk["add Nonfat Milk"]
    Mocha_Large --> Mocha_Large_Nonfat_Milk
    Mocha_Medium["Mocha (Medium)"]
    Coffee_Tea --> Mocha_Medium
    Mocha_Medium_Nonfat_Milk["add Nonfat Milk"]
    Mocha_Medium --> Mocha_Medium_Nonfat_Milk
    Mocha_Small["Mocha (Small)"]
    Coffee_Tea --> Mocha_Small
    Mocha_Small_Nonfat_Milk["add Nonfat Milk"]
    Mocha_Small --> Mocha_Small_Nonfat_Milk
    Nonfat_Caramel_Latte_Large["Nonfat Caramel Latte (Large)"]
    Coffee_Tea --> Nonfat_Caramel_Latte_Large
    Nonfat_Caramel_Latte_Medium["Nonfat Caramel Latte (Medium)"]
    Coffee_Tea --> Nonfat_Caramel_Latte_Medium
    Nonfat_Caramel_Latte_Small["Nonfat Caramel Latte (Small)"]
    Coffee_Tea --> Nonfat_Caramel_Latte_Small
    Nonfat_Caramel_Mocha_Large["Nonfat Caramel Mocha (Large)"]
    Coffee_Tea --> Nonfat_Caramel_Mocha_Large
    Nonfat_Caramel_Mocha_Medium["Nonfat Caramel Mocha (Medium)"]
    Coffee_Tea --> Nonfat_Caramel_Mocha_Medium
    Nonfat_Caramel_Mocha_Small["Nonfat Caramel Mocha (Small)"]
    Coffee_Tea --> Nonfat_Caramel_Mocha_Small
    Nonfat_French_Vanilla_Latte_Large["Nonfat French Vanilla Latte (Large)"]
    Coffee_Tea --> Nonfat_French_Vanilla_Latte_Large
    Nonfat_French_Vanilla_Latte_Medium["Nonfat French Vanilla Latte (Medium)"]
    Coffee_Tea --> Nonfat_French_Vanilla_Latte_Medium
    Nonfat_French_Vanilla_Latte_Small["Nonfat French Vanilla Latte (Small)"]
    Coffee_Tea --> Nonfat_French_Vanilla_Latte_Small
    Nonfat_Hazelnut_Latte_Large["Nonfat Hazelnut Latte (Large)"]
    Coffee_Tea --> Nonfat_Hazelnut_Latte_Large
    Nonfat_Hazelnut_Latte_Medium["Nonfat Hazelnut Latte (Medium)"]
    Coffee_Tea --> Nonfat_Hazelnut_Latte_Medium
    Nonfat_Hazelnut_Latte_Small["Nonfat Hazelnut Latte (Small)"]
    Coffee_Tea --> Nonfat_Hazelnut_Latte_Small
    Nonfat_Latte_Large["Nonfat Latte (Large)"]
    Coffee_Tea --> Nonfat_Latte_Large
    Nonfat_Latte_Large_Sugar_Free_French_Vanilla_Syrup["add Sugar Free French Vanilla Syrup"]
    Nonfat_Latte_Large --> Nonfat_Latte_Large_Sugar_Free_French_Vanilla_Syrup
    Nonfat_Latte_Medium["Nonfat Latte (Medium)"]
    Coffee_Tea --> Nonfat_Latte_Medium
    Nonfat_Latte_Medium_Sugar_Free_French_Vanilla_Syrup["add Sugar Free French Vanilla Syrup"]
    Nonfat_Latte_Medium --> Nonfat_Latte_Medium_Sugar_Free_French_Vanilla_Syrup
    Nonfat_Latte_Small["Nonfat Latte (Small)"]
    Coffee_Tea --> Nonfat_Latte_Small
    Nonfat_Latte_Small_Sugar_Free_French_Vanilla_Syrup["add Sugar Free French Vanilla Syrup"]
    Nonfat_Latte_Small --> Nonfat_Latte_Small_Sugar_Free_French_Vanilla_Syrup
    Regular_Iced_Coffee_Large["Regular Iced Coffee (Large)"]
    Coffee_Tea --> Regular_Iced_Coffee_Large
    Regular_Iced_Coffee_Medium["Regular Iced Coffee (Medium)"]
    Coffee_Tea --> Regular_Iced_Coffee_Medium
    Regular_Iced_Coffee_Small["Regular Iced Coffee (Small)"]
    Coffee_Tea --> Regular_Iced_Coffee_Small
    Sweet_Tea_Child["Sweet Tea (Child)"]
    Coffee_Tea --> Sweet_Tea_Child
    Sweet_Tea_Large["Sweet Tea (Large)"]
    Coffee_Tea --> Sweet_Tea_Large
    Sweet_Tea_Medium["Sweet Tea (Medium)"]
    Coffee_Tea --> Sweet_Tea_Medium
    Sweet_Tea_Small["Sweet Tea (Small)"]
    Coffee_Tea --> Sweet_Tea_Small