graph TD
    Desserts["Desserts"]
    Baked_Apple_Pie["Baked Apple Pie"]
    Desserts --> Baked_Apple_Pie
    Chocolate_Chip_Cookie["Chocolate Chip Cookie"]
    Desserts --> Chocolate_Chip_Cookie
    Hot_Caramel_Sundae["Hot Caramel Sundae"]
    Desserts --> Hot_Caramel_Sundae
    Hot_Fudge_Sundae["Hot Fudge Sundae"]
    Desserts --> Hot_Fudge_Sundae
    Kids_Ice_Cream_Cone["Kids Ice Cream Cone"]
    Desserts --> Kids_Ice_Cream_Cone
    Oatmeal_Raisin_Cookie["Oatmeal Raisin Cookie"]
    Desserts --> Oatmeal_Raisin_Cookie
    Strawberry_Sundae["Strawberry Sundae"]
    Desserts --> Strawberry_Sundae