graph TD
    Smoothies_Shakes["Smoothies & Shakes"]
    Blueberry_Pomegranate_Smoothie_Large["Blueberry Pomegranate Smoothie (Large)"]
    Smoothies_Shakes --> Blueberry_Pomegranate_Smoothie_Large
    Blueberry_Pomegranate_Smoothie_Medium["Blueberry Pomegranate Smoothie (Medium)"]
    Smoothies_Shakes --> Blueberry_Pomegranate_Smoothie_Medium
    Blueberry_Pomegranate_Smoothie_Small["Blueberry Pomegranate Smoothie (Small)"]
    Smoothies_Shakes --> Blueberry_Pomegranate_Smoothie_Small
    Chocolate_Shake_Large["Chocolate Shake (Large)"]
    Smoothies_Shakes --> Chocolate_Shake_Large
    Chocolate_Shake_Medium["Chocolate Shake (Medium)"]
    Smoothies_Shakes --> Chocolate_Shake_Medium
    Chocolate_Shake_Small["Chocolate Shake (Small)"]
    Smoothies_Shakes --> Chocolate_Shake_Small
    Mango_Pineapple_Smoothie_Large["Mango Pineapple Smoothie (Large)"]
    Smoothies_Shakes --> Mango_Pineapple_Smoothie_Large
    Mango_Pineapple_Smoothie_Medium["Mango Pineapple Smoothie (Medium)"]
    Smoothies_Shakes --> Mango_Pineapple_Smoothie_Medium
    Mango_Pineapple_Smoothie_Small["Mango Pineapple Smoothie (Small)"]
    Smoothies_Shakes --> Mango_Pineapple_Smoothie_Small
    McFlurry_Medium["McFlurry (Medium)"]
    Smoothies_Shakes --> McFlurry_Medium
    McFlurry_Medium_M_Ms_Candies["add M&Ms Candies"]
    McFlurry_Medium --> McFlurry_Medium_M_Ms_Candies
    McFlurry_Medium_Oreo_Cookies["add Oreo Cookies"]
    McFlurry_Medium --> McFlurry_Medium_Oreo_Cookies
    McFlurry_Medium_Reeses_Peanut_Butter_Cups["add Reeses Peanut Butter Cups"]
    McFlurry_Medium --> McFlurry_Medium_Reeses_Peanut_Butter_Cups
    McFlurry_Small["McFlurry (Small)"]
    Smoothies_Shakes --> McFlurry_Small
    McFlurry_Small_M_Ms_Candies["add M&Ms Candies"]
    McFlurry_Small --> McFlurry_Small_M_Ms_Candies
    McFlurry_Small_Oreo_Cookies["add Oreo Cookies"]
    McFlurry_Small --> McFlurry_Small_Oreo_Cookies
    McFlurry_Snack["McFlurry (Snack)"]
    Smoothies_Shakes --> McFlurry_Snack
    McFlurry_Snack_M_Ms_Candies["add M&Ms Candies"]
    McFlurry_Snack --> McFlurry_Snack_M_Ms_Candies
    McFlurry_Snack_Oreo_Cookies["add Oreo Cookies"]
    McFlurry_Snack --> McFlurry_Snack_Oreo_Cookies
    McFlurry_Snack_Reeses_Peanut_Butter_Cups["add Reeses Peanut Butter Cups"]
    McFlurry_Snack --> McFlurry_Snack_Reeses_Peanut_Butter_Cups
    Shamrock_Shake_Large["Shamrock Shake (Large)"]
    Smoothies_Shakes --> Shamrock_Shake_Large
    Shamrock_Shake_Medium["Shamrock Shake (Medium)"]
    Smoothies_Shakes --> Shamrock_Shake_Medium
    Strawberry_Banana_Smoothie_Large["Strawberry Banana Smoothie (Large)"]
    Smoothies_Shakes --> Strawberry_Banana_Smoothie_Large
    Strawberry_Banana_Smoothie_Medium["Strawberry Banana Smoothie (Medium)"]
    Smoothies_Shakes --> Strawberry_Banana_Smoothie_Medium
    Strawberry_Banana_Smoothie_Small["Strawberry Banana Smoothie (Small)"]
    Smoothies_Shakes --> Strawberry_Banana_Smoothie_Small
    Strawberry_Shake_Large["Strawberry Shake (Large)"]
    Smoothies_Shakes --> Strawberry_Shake_Large
    Strawberry_Shake_Medium["Strawberry Shake (Medium)"]
    Smoothies_Shakes --> Strawberry_Shake_Medium
    Strawberry_Shake_Small["Strawberry Shake (Small)"]
    Smoothies_Shakes --> Strawberry_Shake_Small
    Vanilla_Shake_Large["Vanilla Shake (Large)"]
    Smoothies_Shakes --> Vanilla_Shake_Large
    Vanilla_Shake_Medium["Vanilla Shake (Medium)"]
    Smoothies_Shakes --> Vanilla_Shake_Medium
    Vanilla_Shake_Small["Vanilla Shake (Small)"]
    Smoothies_Shakes --> Vanilla_Shake_Small