graph TD
    Snacks_Sides["Snacks & Sides"]
    Apple_Slices["Apple Slices"]
    Snacks_Sides --> Apple_Slices
    Chipotle_BBQ_Snack_Wrap_Crispy_Chicken["Chipotle BBQ Snack Wrap (Crispy Chicken)"]
    Snacks_Sides --> Chipotle_BBQ_Snack_Wrap_Crispy_Chicken
    Chipotle_BBQ_Snack_Wrap_Grilled_Chicken["Chipotle BBQ Snack Wrap (Grilled Chicken)"]
    Snacks_Sides --> Chipotle_BBQ_Snack_Wrap_Grilled_Chicken
    Fruit_n_Yogurt_Parfait["Fruit n Yogurt Parfait"]
    Snacks_Sides --> Fruit_n_Yogurt_Parfait
    Honey_Mustard_Snack_Wrap_Crispy_Chicken["Honey Mustard Snack Wrap (Crispy Chicken)"]
    Snacks_Sides --> Honey_Mustard_Snack_Wrap_Crispy_Chicken
    Honey_Mustard_Snack_Wrap_Grilled_Chicken["Honey Mustard Snack Wrap (Grilled Chicken)"]
    Snacks_Sides --> Honey_Mustard_Snack_Wrap_Grilled_Chicken
    Kids_French_Fries["Kids French Fries"]
    Snacks_Sides --> Kids_French_Fries
    Large_French_Fries["Large French Fries"]
    Snacks_Sides --> Large_French_Fries
    Medium_French_Fries["Medium French Fries"]
    Snacks_Sides --> Medium_French_Fries
    Ranch_Snack_Wrap_Crispy_Chicken["Ranch Snack Wrap (Crispy Chicken)"]
    Snacks_Sides --> Ranch_Snack_Wrap_Crispy_Chicken
    Ranch_Snack_Wrap_Grilled_Chicken["Ranch Snack Wrap (Grilled Chicken)"]
    Snacks_Sides --> Ranch_Snack_Wrap_Grilled_Chicken
    Side_Salad["Side Salad"]
    Snacks_Sides --> Side_Salad
    Small_French_Fries["Small French Fries"]
    Snacks_Sides --> Small_French_Fries